### ISSUE TITLE
Broken with Test::Unit - cannot load such file -- minitest/autorun

### ISSUE THREAD

**Issue by pjar** [pivotal/sunspot_matchers#30]
First, thank you for a great gem!  Recently I wanted to update sunspot_solr gem but then tests started to break (wrong number of arguments for `#commit` method). I wanted to see if upgrading sunspot_matchers will help, but after successful bundle update, the tests break with:

```
/bundle/gems/activesupport-3.2.22.1/lib/active_support/dependencies.rb:251:in `require': cannot load such file -- minitest/autorun (LoadError)
	from /bundle/gems/activesupport-3.2.22.1/lib/active_support/dependencies.rb:251:in `block in require'
	from /bundle/gems/activesupport-3.2.22.1/lib/active_support/dependencies.rb:236:in `load_dependency'
	from /bundle/gems/activesupport-3.2.22.1/lib/active_support/dependencies.rb:251:in `require'
	from /bundle/gems/sunspot_matchers-2.2.0.5/lib/sunspot_matchers/test_helper.rb:2:in `<top (required)>'
	from /bundle/gems/activesupport-3.2.22.1/lib/active_support/dependencies.rb:251:in `require'
	from /bundle/gems/activesupport-3.2.22.1/lib/active_support/dependencies.rb:251:in `block in require'
	from /bundle/gems/activesupport-3.2.22.1/lib/active_support/dependencies.rb:236:in `load_dependency'
	from /bundle/gems/activesupport-3.2.22.1/lib/active_support/dependencies.rb:251:in `require'
	from /app/test/unit/searches/browse_product_search_test.rb:2:in `<top (required)>'
	from /bundle/gems/activesupport-3.2.22.1/lib/active_support/dependencies.rb:251:in `require'
	from /bundle/gems/activesupport-3.2.22.1/lib/active_support/dependencies.rb:251:in `block in require'
	from /bundle/gems/activesupport-3.2.22.1/lib/active_support/dependencies.rb:236:in `load_dependency'
	from /bundle/gems/activesupport-3.2.22.1/lib/active_support/dependencies.rb:251:in `require'
	from /bundle/gems/rake-10.5.0/lib/rake/rake_test_loader.rb:10:in `block (2 levels) in <main>'
	from /bundle/gems/rake-10.5.0/lib/rake/rake_test_loader.rb:9:in `each'
	from /bundle/gems/rake-10.5.0/lib/rake/rake_test_loader.rb:9:in `block in <main>'
	from /bundle/gems/rake-10.5.0/lib/rake/rake_test_loader.rb:4:in `select'
	from /bundle/gems/rake-10.5.0/lib/rake/rake_test_loader.rb:4:in `<main>'
```

It would be great if it is possible to revert this change: https://github.com/pivotal/sunspot_matchers/commit/5ded5c7248a037437567c5bfac0107b9d07fe972

As you can see we are on Rails 3.2 and not using minitest. Adding minitest to the Gemfile didn't help as it was not runinng our tests despite the above error disappearance. 

Once again I much appreciate your work! :)

**Comment by jpalermo** [comment]
Hey @pjar,

I'm not super familiar with test_unit these days. Which version of ruby are you using?

**Comment by pjar** [comment]
Hi @jpalermo 

It's ruby 2.2.2. 
I've made it working for me with this change: https://github.com/codequest-eu/sunspot_matchers/commit/7ee4ec7908a4554c4913fac41c91eca45ad6d09b

**Comment by jpalermo** [comment]
I just release gem 2.2.5.0. Let me know if that fixes your problem.

**Comment by pjar** [comment]
@jpalermo - thank you for a quick and prompt response. It indeed fixes my issue. 
Best regards
